on:
  push:
    branches: [main]

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      ASSET_NAME: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: codex-team/action-nodejs-package-info@v1
        id: package
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ steps.package.outputs.name }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false}]'
      - name: ZIP Build
        if: ${{ steps.release.outputs.release_created }}
        run: zip -r $ASSET_NAME.zip build
      - name: Release Artifact Upload
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} $ASSET_NAME.zip
      - name: Release Event Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: vovaspace/probable-palm-tree
          event-type: external_release
          client-payload: '{"tag_name": "${{ steps.release.outputs.tag_name }}", "asset_name": "${{ env.ASSET_NAME }}"}'
